### ISSUE TITLE
Is it possible to add the logged-in User?

### ISSUE THREAD

**Issue by gmgarrison** [jeremykenedy/laravel-exception-notifier#12]
Thank you for this (and all your other!) open-sourced packages.

Forgive my ignorance on the specifics of the Laravel request handling stack, but would it be possible to information in the error report about which, if any, user is logged in? The base case could be a user ID with maybe a configuration option to include more columns from the User table (first, last, email, etc).

I do realize there's no guarantee this information would be available depending on when in the stack the error occurred (or if it came over an API call) but you could just display null for those cases.

What do you think? (If you think it's a good idea but don't have time, I would give it a shot if you can point me where in your package to get started and if I figure it out, I'll submit a PR.)

Thank you!!

**Comment by jeremykenedy** [comment]
You can change the code in handler.php of your app to send it whatever you want to.

**Comment by jeremykenedy** [comment]
Or modify/override the sendmail method

https://github.com/jeremykenedy/laravel-exception-notifier#laravel-9-and-above-1

otherwise this package will send along the error logged with stack stack trace as it would appear in the logs.
